FROM python:3.12-slim

WORKDIR /app

COPY anamnesia/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY anamnesia/ .

RUN mkdir -p /tmp/anamnesia/audio

# Railway passes service variables as Docker build args
ARG GROQ_API_KEY
ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG BACKEND_API_KEY
ARG FLASK_ENV
ARG FLASK_SECRET_KEY
ARG SUPABASE_JWT_SECRET
ARG WHISPER_MODEL
ARG AUDIO_STORAGE_PATH
ARG ANTHROPIC_API_KEY

# Make them available at runtime
ENV GROQ_API_KEY=$GROQ_API_KEY
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY
ENV BACKEND_API_KEY=$BACKEND_API_KEY
ENV FLASK_ENV=$FLASK_ENV
ENV FLASK_SECRET_KEY=$FLASK_SECRET_KEY
ENV SUPABASE_JWT_SECRET=$SUPABASE_JWT_SECRET
ENV WHISPER_MODEL=$WHISPER_MODEL
ENV AUDIO_STORAGE_PATH=$AUDIO_STORAGE_PATH
ENV ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY

CMD gunicorn run:app --bind 0.0.0.0:${PORT:-8080} --workers 1 --timeout 120
