[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r anamnesia/requirements.txt"]

[start]
cmd = "cd anamnesia && gunicorn run:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
